ARG version
FROM almalinux:${version:-7}
ARG sudheer=worstboy
ARG vineela=hardworkingwomen
RUN echo "sudheer is ${sudheer} vineela is ${vineela} "
CMD ["sleep", "100"]



#How can you check OS of your Server? cat /etc/*release